# This is an action that will be used to cache dependencies
# It will be called in the workflow file by passing the path to THIS action
name: Cache Dependencies
description: This Action will cache Dependencies
runs:
  using: "composite" # There are three types of actions, composite, javascript, docker

  #in here we only need two steps,
  # 1- Cache the dependencies
  # 2- Install them from the cache
  steps:
    - name: Cache Dependencies
      id: cache # we use the id to call this step at a later stage in time, (a reference)
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash # for steps that uses run you must specify the shell to be used